//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourAgencyEntities : DbContext
    {
        public TourAgencyEntities()
            : base("name=TourAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Connection> Connections { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Excursion> Excursions { get; set; }
        public virtual DbSet<FoodType> FoodTypes { get; set; }
        public virtual DbSet<GroupTour> GroupTours { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Representative> Representatives { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<HotelRoomType> HotelRoomTypes { get; set; }
        public virtual DbSet<RecreationType> RecreationTypes { get; set; }
    }
}
